# Generated by Django 4.1.7 on 2023-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(max_length=50, unique=True, verbose_name="配置名称"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="配置名称(英文)"
                    ),
                ),
                ("conf_value", models.TextField(verbose_name="配置值")),
                ("remark", models.TextField(verbose_name="配置描述")),
                (
                    "conf_type",
                    models.CharField(default="0", max_length=10, verbose_name="配置分类"),
                ),
            ],
        ),
    ]
