# Generated by Django 4.1.7 on 2023-03-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf_pro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="config",
            table="config",
        ),
    ]
