# Generated by Django 4.2.2 on 2023-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_path", models.CharField(max_length=200)),
                ("content", models.TextField(null=True)),
                ("product_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=22)),
                ("blog", models.URLField()),
                ("create_datetime", models.DateTimeField()),
            ],
        ),
    ]
