# Generated by Django 4.2.2 on 2023-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsModel2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=200)),
                ("content", models.TextField(null=True)),
                ("product_name", models.CharField(max_length=100)),
                ("document_name", models.CharField(max_length=100)),
            ],
        ),
    ]
