# Generated by Django 2.2.28 on 2023-03-01 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 22, 16, 30, 34083)),
        ),
        migrations.AlterModelTable(
            name='serializerdemo',
            table='people',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90, verbose_name='Title (*)')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('status', models.CharField(blank=True, choices=[('p', 'Published'), ('d', 'Draft')], default='s', max_length=1, null=True, verbose_name='Status (*)')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['-create_date'],
            },
        ),
    ]
