# Generated by Django 2.1.5 on 2023-03-19 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_pro', '0002_auto_20230301_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 0, 37, 55, 615138)),
        ),
    ]
