# Generated by Django 2.2 on 2023-04-04 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_pro', '0003_auto_20230320_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 23, 59, 31, 393073)),
        ),
    ]
