# Generated by Django 3.2.18 on 2023-07-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_pro', '0004_auto_20230404_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 18, 3, 24, 255202)),
        ),
    ]
