# Generated by Django 3.2.18 on 2023-07-19 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_pro', '0006_alter_serializerdemo_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 18, 52, 3, 724816)),
        ),
    ]
