# Generated by Django 3.2.18 on 2023-07-20 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_pro', '0007_alter_serializerdemo_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializerdemo',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 9, 12, 32, 148249)),
        ),
    ]
